### ISSUE TITLE
Screenshot for pelicanthemes.com catalog

### ISSUE THREAD

**Issue by philshem** [ivanhercaz/buruma#27]
Cool theme!

Please consider adding some screenshot(s) to the repo home folder. Buruma will then be indexed and shown on the catalog site: http://www.pelicanthemes.com/

> This site searches for screenshots in the root folder of the theme GitHub repository. These are the themes that screenshots couldn't be found for.

Related: https://github.com/ivanhercaz/buruma/issues/15#issuecomment-563629787

**Comment by ivanhercaz** [comment]
> Cool theme!

Thank you very much @philshem! I have seen you used a very interesting Bulma-based theme, [Bulrush](https://github.com/textbook/bulrush) created by @textbook, in [your website](https://github.com/philshem/smalldata.github.io). That theme is more mature and I really like it, so probably I will use it to inspire new improvements for Buruma.

> Please consider adding some screenshot(s) to the repo home folder. Buruma will then be indexed and shown on the catalog site: http://www.pelicanthemes.com/

Oh yes! I forget to add the screenshots as I said in #15. Thank you very much for remember this. I will add them as soon as possible, probably today.

**P.S.** I really like the idea of build a Pelican theme as a Python package and install it with `pip install THEME`, as it is indicated in Bulrush's docs.

**Comment by ivanhercaz** [comment]
@philshem, I already added two screenshots for Buruma with the commit that closed this issue. Please, if you consider that I should specify something in the filenames or add more screenshots, ask me for that. And again, thank you very much for the creation of this issue :heart:
