### ISSUE TITLE
Tag error in author, category and tag templates

### ISSUE THREAD

**Issue by e-belair** [ivanhercaz/buruma#31]
You have to choose between h1 or h2 ;-)
https://github.com/ivanhercaz/buruma/blob/8f77ca599831d3016caeeb8eaa5ebb35769bcddc/templates/category.html#L8

**Comment by ivanhercaz** [comment]
Ups! A little slip! I will fix it as soon as possible.

**Comment by ivanhercaz** [comment]
This problem is also in the template for each tag (`tag.html`):

https://github.com/ivanhercaz/buruma/blob/8f77ca599831d3016caeeb8eaa5ebb35769bcddc/templates/tag.html#L8

So I am going to rename this issue.

**Comment by ivanhercaz** [comment]
And in the template for each author (`author.html`):

https://github.com/ivanhercaz/buruma/blob/8f77ca599831d3016caeeb8eaa5ebb35769bcddc/templates/author.html#L8

**Comment by ivanhercaz** [comment]
Thank you very much for this report, @e-belair :)
