### ISSUE TITLE
h1 elements are not styled

### ISSUE THREAD

**Issue by maciejmatczak** [ivanhercaz/buruma#32]
Hello,
Just came across an issue, as in title. In `style.scss` there is no style statement for h1, hence it looks almost like a normal text.

Code on left, browser on the right, it's a part from an article:
![image](https://user-images.githubusercontent.com/1786383/73923780-b5919780-48cb-11ea-8bed-d027524f7de2.png)

**Comment by ivanhercaz** [comment]
Hi @maciejmatczak! Thank you very much for this report. It is very useful, not just to add the `h1` style, but for another headings styles such as `h5` and `h6`. Today I am going to work on this and I will release a new version before the end of the day.

My idea is to use the Bulma element [`title`](https://bulma.io/documentation/elements/title/) with the size especification (`is-*`). As you can see in the screenshot below, `h4`, `h5` and `h6` have a strange style so I need to specify some details as `margin-top` and not `margin-bottom`.
![entry_about_a_cat_buruma_documentation](https://user-images.githubusercontent.com/8690921/73931806-d6102080-48d0-11ea-8d23-7745078a02f4.png)

I am open to any idea!

**Comment by maciejmatczak** [comment]
Hi @ivanhercaz, thanks for reply.

It looks like those are not supposed to be nested at all :D. Maybe ignore it and just use `is-size-1`? If you would still like to use it, maybe some html attribute conditionals:
```css
p + .title.is-1 {
  margin-top: 2rem;
}
```

**Comment by ivanhercaz** [comment]
The idea is to related each heading with each `is-size`. Currently there is already a SCSS block that works fine with `h2` and `h3`.

https://github.com/ivanhercaz/buruma/blob/fb47c3eee980a535e0cc348ead80af21cf417d0c/static/scss/style.scss#L32-L42

My idea is to apply same `margin-top` for every heading and then reduce the `margin-bottom` progressively. I think `h1`, `h2` and `h3` are fine, although I need to change the last two to `is-2` and `is-3` respectively. But I think `h4`, `h5` and `h6` should have a minimum `margin-bottom` and a reduced `margin-top` to 1rem (I have to test it yet).

What do you think @maciejmatczak?

**Comment by ivanhercaz** [comment]
@maciejmatczak, one question, what version of Buruma are you using? v. 0.1.0 (via pelican-themes) or 0.2.1 (via the master branch of this repository)?

**Comment by ivanhercaz** [comment]
Another question: `title` class makes headings stronger that I usually use it, this is why I extend `h2` and `h3` with `subtitle` instead of `title`. I am going to perform this changes according to this, but I really want to read your opinion about it.

**Comment by maciejmatczak** [comment]
Hmmm, `0.2.1` as far as I remember.

Checkout the fiddle. Raw bulma, headers with `subtitle is-*` vs `is-size-*` (these are separate classes https://bulma.io/documentation/modifiers/typography-helpers/), accordingly:
https://jsfiddle.net/0jvo135g/2/

After you applying `margin-top`, is it any difference?

**Comment by ivanhercaz** [comment]
Ups, excuse me I didn't read it until I already made a PR with a proposal. Yes, I know they are separate classes. The difference between `subtitle is-*` and `is-size-*` is a very little change in the margin-top.

The reason why I I decide to use `subtitle` and `is-*` is because I adapt it with more `margin-top` and with less `margin-bottom`, changing this values just in `.subtitle` class, in that way it isn't necessary to change in each tag, just extend them. I think it is a cleaner way.

Could you check the PR I opened (#34) for this? Thank you a lot for your participation. I am really happy that Buruma has your attention :heart:
